# Build settings
markdown: kramdown
permalink: :title
highlighter: rouge
gems:
  - jemoji
  - jekyll-sitemap

# Site settings
url: http://osem.io
title: Open Source Event Manager
description: "Event management tailored for Free and Open Source community conferences."
excerpt_separator: <!-- more -->
