version: "2.4"

services:
  database:
    image: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: $OSEM_DB_PASSWORD
  osem:
    build:
      context: .
      args:
        CONTAINER_USERID: 1000
    command: /osem/bin/osem-init.sh
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - .:/osem
