version: "2.4"

services:
  database:
    image: postgres:16-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: mysecretpassword
  osem:
    build:
      context: .
      args:
        CONTAINER_USERID: 1000
    command: foreman start -p 3000
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - .:/osem
